name: Sync station log
on:
  push:
    branches:
      - main
    paths:
      - Master_Stations.csv

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Install Hakai Datasets
          run: |
            python -m pip install --upgrade pip
            pip install poetry
            poetry install
        - name: Sync station log
          run: |
            poetry run python scripts/join_master_station_to_station_log.py
        - name: Commit and push changes
          run: |
            git config --global user.email "hakai-it"
            git config --global user.name "hakai-it@users.noreply.github.com"
            git commit -am "Sync station log"
            git push

